# Generated by Django 5.0.1 on 2024-01-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('secondname', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_no', models.CharField(max_length=15)),
                ('member_no', models.CharField(max_length=250, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('reg_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
