# Generated by Django 5.0.1 on 2024-01-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='active',
            new_name='status',
        ),
        migrations.AddField(
            model_name='members',
            name='id_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
