# Generated by Django 5.0.1 on 2024-02-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0002_rename_amount_cont_allcontributions_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcontributions',
            name='cont_id',
            field=models.IntegerField(),
        ),
    ]
