# Generated by Django 5.0.1 on 2024-02-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0004_rename_allcontributions_allcontribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcontribution',
            name='member_no',
            field=models.CharField(blank=True, max_length=255, null=True, unique=False),
        ),
    ]
