# Generated by Django 5.0.1 on 2024-02-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0007_alter_allcontribution_member_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcontribution',
            name='member_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
